CREATE TABLE UTILISATEUR (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    mdp TEXT NOT NULL,
    pseudo TEXT NOT NULL,
    date_naissance DATE NOT NULL,
    grade INTEGER
);

CREATE TABLE LIVRE (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    titre INTEGER NOT NULL,
    genre INTEGER NOT NULL,
    rayon TEXT NOT NULL,
    date_parution DATE NOT NULL,
    uid_nfc TEXT NOT NULL UNIQUE,
    nom_image TEXT NOT NULL
);

CREATE TABLE EMPRUNT (
    id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    id_u INTEGER NOT NULL,
    id_l INTEGER NOT NULL,
    date_debut DATE NOT NULL,
    date_fin DATE NOT NULL,
    rendu BOOLEAN,
    FOREIGN KEY (id_u) REFERENCES UTILISATEUR(id) ON DELETE CASCADE,
    FOREIGN KEY (id_l) REFERENCES LIVRE(id) ON DELETE CASCADE
);